### ISSUE TITLE
deprecated import from sklearn

### ISSUE THREAD

**Issue by huy29433** [braindynamicslab/dyneusr#15]
In _trefoil.py_ and _wrappers.py_, one tries to import `Bunch `from `sklearn.datasets.base`, which has been moved to `sklearn.utils`.

**Comment by calebgeniesse** [comment]
hi @huy29433, thanks for reporting!

i thought this issue had been resolved by a recent pull request (#14), but let me know if not 

maybe try pulling, or re-cloning the codebase before running again

**Comment by huy29433** [comment]
Hi, yes you're absolutely right, I still had an old version! Sorry and thank you!
